# Site settings
title: 艾里克de梦
layout: posts
email: pyericz@yahoo.com 
description: "人生最曼妙的风景，不是命运的波澜，而是内心的淡定与从容"
baseurl: ""
url: "http://pyericz.github.io"
github_username:  pyericz
timezone: Asian/Shanghai

author: Eric Zhang

# Build settings
markdown: kramdown
permalink: pretty

highlighter: pygments
github: https://github.com/pyericz/pyericz.github.io.git
